name: Generate Monkeytype README SVG

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download-svg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download SVGs
        run: |
          set -e
          mkdir -p public

          curl -fL "https://monkeytype-readme.com/generate-svg/TheLinuxGuy-ssh/shadow" -o public/monkeytype-readme.svg
          curl -fL "https://monkeytype-readme.com/generate-svg/TheLinuxGuy-ssh/shadow?lb=true" -o public/monkeytype-readme-lb.svg
          curl -fL "https://monkeytype-readme.com/generate-svg/TheLinuxGuy-ssh/shadow?pb=true" -o public/monkeytype-readme-pb.svg
          curl -fL "https://monkeytype-readme.com/generate-svg/TheLinuxGuy-ssh/shadow?lbpb=true" -o public/monkeytype-readme-lb-pb.svg

      - name: Deploy SVGs
        uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: monkeytype-readme
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
